language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9,<1.10'
  - DJANGO='django>=1.10,<1.11'
  - DJANGO='django>=1.11,<1.2'
  - DJANGO='django>=2.0.6'

install:
  - make install
  - pip install $DJANGO

script:
    make test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
